const TYPES = {
    //DTConfig
    GET_DTCONFIGS: "GET_DTCONFIGS",
    GET_DTCONFIG: "GET_DTCONFIG",
    ADD_DTCONFIG: "ADD_DTCONFIG",
    UPDATE_DTCONFIG: "UPDATE_DTCONFIG",
    DELETE_DTCONFIG: "DELETE_DTCONFIG",
    DISABLE_DTCONFIG: "DISABLE_DTCONFIG",
    INIT_DTCONFIG: "INIT_DTCONFIG",
    //STConfig
    GET_STCONFIGS: "GET_STCONFIGS",
    GET_STCONFIG: "GET_STCONFIG",
    ADD_STCONFIG: "ADD_STCONFIG",
    UPDATE_STCONFIG: "UPDATE_STCONFIG",
    DELETE_STCONFIG: "DELETE_STCONFIG",
    DISABLE_STCONFIG: "DISABLE_STCONFIG",
    INIT_STCONFIG: "INIT_STCONFIG",
    //GTConfig
    GET_GTCONFIGS: "GET_GTCONFIGS",
    GET_GTCONFIG: "GET_GTCONFIG",
    ADD_GTCONFIG: "ADD_GTCONFIG",
    UPDATE_GTCONFIG: "UPDATE_GTCONFIG",
    DELETE_GTCONFIG: "DELETE_GTCONFIG",
    DISABLE_GTCONFIG: "DISABLE_GTCONFIG",
    INIT_GTCONFIG: "INIT_GTCONFIG",
    // Functions
    SET_EDIT_MODE_ON: "SET_EDIT_MODE_ON",
    SET_EDIT_MODE_OFF: "SET_EDIT_MODE_OFF",
    REFRESH_ON: "REFRESH_ON",
    REFRESH_OFF: "REFRESH_OFF"
}

export default TYPES